---
name: background_pipeline_retry_endpoint
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/61270
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/330915
milestone: '13.12'
type: development
group: group::pipeline authoring
default_enabled: false
