---
name: boards_filtered_search
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54641
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/322778
milestone: '13.10'
type: development
group: group::project management
default_enabled: false
