---
name: cached_sidebar_open_epics_count
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/58064
rollout_issue_url:
milestone: '13.11'
type: development
group: group::product planning
default_enabled: true
