---
name: ci_external_validation_service
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56856
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323935
milestone: '13.11'
type: development
group: group::continuous integration
default_enabled: false
