---
name: gitlab_ci_trace_read_consistency
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46976
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/320938
milestone: '13.9'
type: development
group: group::continuous integration
default_enabled: true
