---
name: gitlab_ci_builds_queue_limit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54579
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323201
milestone: '13.10'
type: development
group: group::continuous integration
default_enabled: true
