---
name: load_balancing_for_build_hooks_worker
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57575
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/326095
milestone: '13.11'
type: development
group: group::memory
default_enabled: false
