---
name: merge_request_cached_merge_pipeline_serializer
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57827
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/326317
milestone: '13.11'
type: development
group: group::source code
default_enabled: false
