---
name: notification_setting_recipient_refactor
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57688
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/327303
milestone: '13.11'
type: development
group: group::code review
default_enabled: true
