---
name: pipeline_filter_jobs
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/57142
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/325693
milestone: '13.11'
type: development
group: group::pipeline authoring
default_enabled: false
