---
name: project_statistics_sync
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/29636
rollout_issue_url: 
milestone: '12.10'
type: development
group: group::source code
default_enabled: true
