---
name: usage_data_code_review_aggregation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/53553
rollout_issue_url: 
milestone: '13.9'
type: development
group: group::code review
default_enabled: true
