---
name: usage_data_track_ecosystem_jira_service
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/52110
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/300447
milestone: '13.9'
type: development
group: group::ecosystem
default_enabled: false
