---
name: cve_id_request_button
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/41203
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/299569
milestone: '13.10'
type: development
group: group::vulnerability research
default_enabled: false
