---
name: productivity_analytics_scatterplot_enabled
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17735
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/13412
milestone: '12.4'
type: development
group: group::optimize
default_enabled: true
