---
key_path: license_trial_ends_on
description: Date the license ends on
product_section: growth
product_stage: growth
product_group: group::product intelligence
product_category: collection
value_type: string
status: data_available
time_frame: none
data_source: system
distribution:
- ce
tier:
- free
skip_validation: true
