---
key_path: git.version
description: ''
product_section: ''
product_stage: ''
product_group: ''
product_category: ''
value_type: string
status: data_available
time_frame: none
data_source: system
distribution:
- ce
tier:
- free
skip_validation: true
