---
key_path: container_registry_server.version
description: Identifies the version of the external registry being used
product_section: ops
product_stage: package
product_group: group::package
product_category:
value_type: string
status: data_available
time_frame: none
data_source: system
distribution:
- ce
tier:
- free
skip_validation: true
