---
key_path: usage_activity_by_stage_monthly.secure.dependency_scanning_pipeline
description: no idea, what is this when did it get added? guess pipelines containing
  a DS job
product_section: sec
product_stage: secure
product_group: group::composition analysis
product_category: dependency_scanning
value_type: number
status: data_available
time_frame: 28d
data_source:
distribution:
- ee
tier:
- ultimate
skip_validation: true
