---
key_path: counts.projects_with_packages
description: Projects with package registry configured
product_section: ops
product_stage:
product_group: group::package
product_category:
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
skip_validation: true
