---
key_path: counts.status_page_incident_unpublishes
description: Cumulative count of usages of unpublish operation
product_section: ops
product_stage: monitor
product_group: group::health
product_category: incident_management
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
skip_validation: true
