---
key_path: counts.static_site_editor_commits
description: Count of commits created via Static Site Editor
product_section: dev
product_stage: create
product_group: group::editor
product_category: static_site_editor
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
tier:
- free
skip_validation: true
