---
key_path: counts.secret_detection_jobs
description: Count of 'secret-detection' CI jobs fro the month.
product_section: sec
product_stage: secure
product_group: group::static analysis
product_category: secret_detection
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
