---
key_path: counts.project_snippets
description: Count of Project Snippetss
product_section: dev
product_stage: create
product_group: group::editor
product_category: snippets
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
