---
key_path: usage_activity_by_stage.package.projects_with_packages
description: Projects with package registry configured
product_section: ops
product_stage: package
product_group: group::package
product_category:
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ce
tier:
- free
skip_validation: true
