---
key_path: counts.user_preferences_user_gitpod_enabled
description: Count all users with their GitPod setting enabled
product_section: dev
product_stage: create
product_group: group::editor
product_category: editor_extension
value_type: number
status: data_available
time_frame: all
data_source: database
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
