---
key_path: usage_activity_by_stage.create.snippets
description: Snippets
product_section: dev
product_stage: create
product_group: group::editor
product_category: snippets
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
