---
key_path: counts_weekly.aggregated_metrics.incident_management_alerts_total_unique_counts
description: Count of unique users per week to take an action on an alert
product_section: ops
product_stage: monitor
product_group: group::health
product_category: incident_management
value_type: number
status: data_available
time_frame: 7d
data_source: database
distribution:
- ee
tier: []
skip_validation: true
