---
key_path: usage_activity_by_stage_monthly.create.action_monthly_active_users_ide_edit
description: Count unique edit actions when users used an IDE, no matter which one
product_section: dev
product_stage: create
product_group: group::editor
product_category: web_ide
value_type: number
status: data_available
time_frame: 28d
data_source:
distribution:
- ce
tier:
- free
skip_validation: true
