---
name: ci_queueing_disaster_recovery
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/56658
rollout_issue_url:
milestone: "13.12"
type: ops
group: group::continuous integration
default_enabled: false
