---
key_path: usage_activity_by_stage.manage.value_stream_management_customized_group_stages
description:
product_section: dev
product_stage:
product_group: group::manage
product_category:
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ee
tier: []
skip_validation: true
