---
key_path: usage_activity_by_stage.manage.ldap_servers
description: Number of LDAP servers configured for the instance `https://docs.gitlab.com/ee/administration/auth/ldap/#multiple-ldap-servers`
product_section: dev
product_stage:
product_group: group::manage
product_category:
value_type: number
status: data_available
time_frame: all
data_source:
distribution:
- ee
tier: []
skip_validation: true
