---
key_path: object_store.uploads.enabled
description: Whether Object Storage is enabled for Uploads
product_section: enablement
product_stage: enablement
product_group: group::memory
product_category: operational_metrics
value_type: string
status: data_available
time_frame: all
data_source: system
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
skip_validation: true
